import { IndexRuleItem } from '../../../services/pool/connectionPoolTypes';

export const COMPREHENSIVE_INDEX_RULES: IndexRuleItem[] = [
  {
    collection: '/codes',
    indexes: ['status', 'category', 'language', 'updatedAt', 'createdAt', 'authorId', 'views', 'averageRating', 'isFeatured', 'isPopular'],
    purpose: 'Instant filtering for published tools, category searches, creator portfolios, and sorting by popularity',
    queryPattern: "orderByChild('status').equalTo('active') & orderByChild('views')",
    priority: 'critical',
    frequency: 'Continuous (~85% of all reads)',
  },
  {
    collection: '/events',
    indexes: ['status', 'isPopup', 'createdAt', 'updatedAt', 'price', 'downPrice'],
    purpose: 'Active warning notices, popup banner detection, and masterclass registration filters',
    queryPattern: "orderByChild('isPopup').equalTo(true)",
    priority: 'critical',
    frequency: 'On each visitor app entry (~100%)',
  },
  {
    collection: '/banners',
    indexes: ['active', 'order', 'createdAt'],
    purpose: 'Zero-latency slider banners sequencing and active state real-time queries',
    queryPattern: "orderByChild('active').equalTo(true) & orderByChild('order')",
    priority: 'high',
    frequency: 'Home page carousel mount',
  },
  {
    collection: '/toolReviews',
    indexes: ['userId', 'rating', 'createdAt'],
    purpose: 'High-speed aggregate ratings calculation and user review tracking without full table scans',
    queryPattern: "orderByChild('userId').equalTo(uid)",
    priority: 'high',
    frequency: 'Tool details review section',
  },
  {
    collection: '/users',
    indexes: ['email', 'role', 'createdAt', 'uid'],
    purpose: 'Authentication lookups, role-based access validation (Admin/Creator/Seller) and user directories',
    queryPattern: "orderByChild('email').equalTo(email)",
    priority: 'critical',
    frequency: 'Login, token refresh, and RBAC guard',
  },
  {
    collection: '/withdrawals',
    indexes: ['userId', 'status', 'createdAt'],
    purpose: 'Creator payout queues, pending approval filters, and transaction history tracking',
    queryPattern: "orderByChild('status').equalTo('pending')",
    priority: 'high',
    frequency: 'Admin payout review & Creator wallet',
  },
  {
    collection: '/creators',
    indexes: ['username', 'verified', 'status', 'createdAt'],
    purpose: 'Public creator handle resolution, verification checks, and author directories',
    queryPattern: "orderByChild('username').equalTo(handle)",
    priority: 'high',
    frequency: 'Creator profile routing /creator/:username',
  },
  {
    collection: '/licenses',
    indexes: ['key', 'codeId', 'status', 'sellerId', 'assignedUserId'],
    purpose: 'Instant license key validation, seller distribution checks, and anti-fraud activation guards',
    queryPattern: "orderByChild('key').equalTo(licenseKey)",
    priority: 'critical',
    frequency: 'Key redemption & Seller inventory',
  },
  {
    collection: '/announcements',
    indexes: ['active', 'createdAt', 'priority'],
    purpose: 'Top banner alert broadcasting across the site with real-time dismiss states',
    queryPattern: "orderByChild('active').equalTo(true)",
    priority: 'medium',
    frequency: 'Global banner subscriber',
  },
];
